network:
  version: 2
  renderer: networkd
  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - 10.1.0.4/24
      routes:
        - to: default
          via: 10.1.0.1
          metric: 100
      nameservers:
        addresses: [10.1.0.2, 8.8.8.8, 8.8.4.4]
