network:
  version: 2
  renderer: networkd
  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - 10.1.10.131/25
      routes:
        - to: default
          via: 10.1.10.129
          metric: 100
      nameservers:
        addresses: [10.1.10.129, 8.8.8.8, 8.8.4.4]
